AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-service

  SAM Template for ai-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Parameters:
  StabilityAPIHost:
    Type: String
    Description: "Base URL for Stability API"
    Default: "replace-me"
  StabilityAPIHostGen:
    Type: String
    Description: "Base URL for Stability API for generating images"
    Default: "replace-me"
  StabilityAPIKey:
    Type: String
    Description: "API Key for Stability API"
    Default: "api-key"
  StageName:
    Type: String
    Description: "The deployment stage name (e.g., Dev, Stage, Prod)"
    Default: ""
  ServiceName:
    Type: String
    Description: "The name of the service"
    Default: ""

Resources:
  AIServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./app/
      Handler: main.handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          STABILITY_API_HOST: !Ref StabilityAPIHost
          STABILITY_API_HOST_GEN: !Ref StabilityAPIHostGen
          STABILITY_API_KEY: !Ref StabilityAPIKey
          ENV: !Ref StageName
          SERVICE_NAME: !Ref ServiceName
      Events:
        AIService:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: 
              Ref: AIServiceHttpApi
        

  AIServiceHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiEndpoint:
    Description: API Gateway endpoint URL for AI Service function
    Value: !Sub "https://${AIServiceHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/${ServiceName}/"
  AIServiceFunction:
    Description: AI Service Lambda Function for generating images and text ARN
    Value: !GetAtt AIServiceFunction.Arn
    Export:
      Name: AIServiceFunction
  AIServiceFunctionIamRole:
    Description: Implicit IAM Role created for AI Service function
    Value: !GetAtt AIServiceFunctionRole.Arn
